;~ ##########################################################################
;~ Copyright (c) 2014 Ulf-Dirk Stockburger
;~ ##########################################################################

;~ Variibles without values aren't listed.
Global vaultCommandID=vaultCommandID ;~Gets the command ID count.
Global vaultIsLoggedIn=vaultIsLoggedIn ;~Gets whether you are logged in to this vault.
Global vaultLanguage=vaultLanguage ;~Gets the language used by the SolidWorks Enterprise PDM client.
Global vaultName=vaultName ;~Gets the name of this vault.
Global vaultRootFolder=vaultRootFolder ;~Gets the root folder of this vault.
Global vaultRootFolderID=vaultRootFolderID ;~Gets the database ID of the root folder of this vault.
Global vaultRootFolderPath=vaultRootFolderPath ;~Gets the file system path to the root folder of this vault.
Global vaultSilentMode=vaultSilentMode ;~Gets whether the add-in is running in silent mode.  
Global vaultClientType=vaultClientType ;~Gets the type of client installation.
Global vaultItemRootFolder=vaultItemRootFolder ;~Gets the interface to the invisible root folder of all items and item folders.
Global vaultItemRootFolderID=vaultItemRootFolderID ;~Gets the ID of the invisible root folder of all items and item folders.
Global userFullName=userFullName ;~Gets this user's full name.
Global userInitials=userInitials ;~Gets this user's initials.
Global userUserData=userUserData ;~Gets and sets arbitrary text data associated with this user.
Global userEmail=userEmail ;~Gets this user's e-mail address
Global userID=userID ;~Gets this user's ID.
Global userGroupIds=userGroupIds ;~Gets the ids of the user's groups.
Global userGroupNames=userGroupNames ;~Gets the names of the user's groups.
Global fileCurrentRevision=fileCurrentRevision ;~Gets the file's current revision.  
Global fileCurrentStateName=fileCurrentStateName 
Global fileCurrentStateID=fileCurrentStateID 
Global fileCurrentVersion=fileCurrentVersion ;~Gets the file's current version number.  
Global fileID=fileID ;~Gets the database ID of this file.
Global fileIsLocked=fileIsLocked ;~Gets whether the file is checked out.  
Global fileLockedByUser=fileLockedByUser ;~Gets the user who has the file checked out.  
Global fileLockedByUserID=fileLockedByUserID ;~Gets the ID of the user who has the file checked out.  
Global fileLockedInFolder=fileLockedInFolder ;~Gets the folder in which this file is checked out.  
Global fileLockedInFolderID=fileLockedInFolderID ;~Gets the ID of the folder in which this file is checked out.  
Global fileLockedOnComputer=fileLockedOnComputer ;~Gets the name of the computer to which the file is checked out.  
Global fileLockPath=fileLockPath ;~Gets the full path to the checked-out file.
Global fileName=fileName ;~Gets the name of the file.
Global fileObjectType=fileObjectType ;~Gets the type of object.  
Global fileCategoryName=fileCategoryName ;~Gets the ID of the category to which this file belongs.
Global fileCategoryID=fileCategoryID ;~Gets the ID of the category to which this file belongs.
Global fileFileType=fileFileType ;~Gets the type of this file.
Global cardButtonNameOfAddInToCall=cardButtonNameOfAddInToCall ;~ID of file data card
Global cardButtonID=cardButtonID ;~ID of file data card
Global cardButtonActiveConfiguration=cardButtonActiveConfiguration ;~Name of active configuration; can be changed to switch to a new configuration
Global cardButtonEdmCardFlag=cardButtonEdmCardFlag ;~Optionally return a EdmCardFlag return code here
Global cardButtonControlId=cardButtonControlId ;~Optionally return the ID of a card control to set focus to here
Global cardButtonAllFileConfigurations=cardButtonAllFileConfigurations ;~List with the names of all configurations
Global cardInputModifiedControlID=cardInputModifiedControlID ;~ID of the modified card control
Global cardInputCardID=cardInputCardID ;~ID of the card
Global cardInputActiveConfiguration=cardInputActiveConfiguration ;~Name of the active configuration
Global cardInputUpdatedVariable=cardInputUpdatedVariable ;~ID of the updated variable
Global cardInputAllFileConfigurations=cardInputAllFileConfigurations ;~List with the names of all configurations
Global cardInputVariableName=cardInputVariableName ;~Name of the variable
Global cardListSrcControlID=cardListSrcControlID ;~ID of the modified card control
Global cardListSrcCardID=cardListSrcCardID ;~ID of the card
Global cardListSrcActiveConfiguration=cardListSrcActiveConfiguration ;~Name of the active configuration
Global cardListSrcControlVariableName=cardListSrcControlVariableName ;~Name of the Control variable
Global cardListSrcControlVariableID=cardListSrcControlVariableID ;~ID of the Control variable
Global cardListSrcAllFileConfigurations=cardListSrcAllFileConfigurations ;~List with the names of all configurations
Global preAddParentFolderID=preAddParentFolderID ;~ID of parent folder
Global preAddLocalFileName=preAddLocalFileName ;~Local file path
Global preAddSourceFileName=preAddSourceFileName ;~Source file path, if copied or moved
Global preAddNetworkSharingLinks=preAddNetworkSharingLinks ;~0 for normal files; 1 for network sharing links
Global postAddParentFolderID=postAddParentFolderID ;~ID of parent folder
Global postAddNetworkSharingLinks=postAddNetworkSharingLinks ;~0 for normal files; 1 for network sharing links
Global preLockParentFolderID=preLockParentFolderID ;~ID of folder where put checked-out file
Global postLockParentFolderID=postLockParentFolderID ;~ID of folder where put checked-out file
Global preAddFolderParentFolderID=preAddFolderParentFolderID ;~ID of parent folder
Global preAddFolderNewFolderName=preAddFolderNewFolderName ;~Path to new folder
Global postAddFolderFolderID=postAddFolderFolderID ;~ID of new folder
Global postAddFolderParentFolderID=postAddFolderParentFolderID ;~ID of parent folder
Global postAddFolderNewFolderName=postAddFolderNewFolderName ;~Path to new folder
Global preCopyFolderDestinationID=preCopyFolderDestinationID ;~ID of destination folder
Global preCopyFieID=preCopyFieID ;~ID of File
Global preCopySourceFolderID=preCopySourceFolderID ;~ID of source folder
Global preCopySourceFileName=preCopySourceFileName ;~Source file path
Global preCopyDestinationFileName=preCopyDestinationFileName ;~Destination file path
Global postCopySourceFolderID=postCopySourceFolderID ;~ID of source folder
Global postCopySourceFileName=postCopySourceFileName ;~Source file path
Global preCopyFolderSourceFolderID=preCopyFolderSourceFolderID ;~ID of source folder
Global preCopyFolderDestinationParentFolderID=preCopyFolderDestinationParentFolderID ;~ID of destination folder
Global preCopyFolderNewFolderName=preCopyFolderNewFolderName ;~Path to new folder
Global postCopyFolderFolderID=postCopyFolderFolderID ;~ID of new folder
Global postCopyFolderSourceFolderID=postCopyFolderSourceFolderID ;~ID of source folder
Global postCopyFolderParentFolderID=postCopyFolderParentFolderID ;~ID of the parent folder
Global postCopyFolderFolderName=postCopyFolderFolderName ;~ID of the parent folder
Global preDeleteParentFolder=preDeleteParentFolder ;~ID of folder to delete file in
Global postDeleteDeletedFileID=postDeleteDeletedFileID ;~ID of file that was deleted
Global postDeleteParetnFolderID=postDeleteParetnFolderID ;~ID of parent folder of the deleted file
Global postDeleteDeletedFileName=postDeleteDeletedFileName ;~Path to file that was deleted
Global postDeleteNumberOfFoldersInWhichItWasShared=postDeleteNumberOfFoldersInWhichItWasShared ;~Number of folders to which the file is shared
Global preDeleteFolderFolderID=preDeleteFolderFolderID ;~ID of folder to Delete
Global preDeleteFolderFolderName=preDeleteFolderFolderName ;~Path to folder to delete
Global postDeleteFolderFolderID=postDeleteFolderFolderID ;~ID of folder to Delete
Global postDeleteFolderFolderName=postDeleteFolderFolderName ;~Path to folder to delete
Global preGetFolderID=preGetFolderID ;~ID of folder to get file to; 0 to retrieve a file to a temporary folder
Global postGetFolderID=postGetFolderID ;~ID of folder to get file to; 0 to retrieve a file to a temporary folder
Global preMoveSourceFolderID=preMoveSourceFolderID ;~ID of source folderID of source folder
Global preMoveDestinationFolderID=preMoveDestinationFolderID ;~ID of destination folder
Global preMoveDestinationFileName=preMoveDestinationFileName ;~Destination file path
Global postMoveSourceFolderID=postMoveSourceFolderID ;~ID of source folderID of source folder
Global postMoveDestinationFolderID=postMoveDestinationFolderID ;~ID of destination folder
Global postMoveSourceFileName=postMoveSourceFileName ;~Source file path
Global preMoveFolderFolderID=preMoveFolderFolderID ;~ID of folder to move
Global preMoveFolderSourceParentFolderID=preMoveFolderSourceParentFolderID ;~ID of source parent folder
Global preMoveFolderDestinationParentFolderID=preMoveFolderDestinationParentFolderID ;~ID of destination parent folder
Global preMoveFolderSourceFolderName=preMoveFolderSourceFolderName ;~ID of folder to move
Global preMoveFolderDestinationFolderName=preMoveFolderDestinationFolderName ;~Destination folder path
Global postMoveFolderFolderID=postMoveFolderFolderID ;~ID of folder to move
Global postMoveFolderSourceParentFolderID=postMoveFolderSourceParentFolderID ;~ID of source parent folder
Global postMoveFolderDestinationParentFolderID=postMoveFolderDestinationParentFolderID ;~ID of destination parent folder
Global postMoveFolderSourceFolderName=postMoveFolderSourceFolderName ;~ID of folder to move
Global postMoveFolderDestinationFolderName=postMoveFolderDestinationFolderName ;~Destination folder path
Global preRenameFileToRenameID=preRenameFileToRenameID ;~ID of the file to rename
Global preRenameFilesParentFolderID=preRenameFilesParentFolderID ;~ID of the file's parent folder
Global preRenameNewFileName=preRenameNewFileName ;~New file name
Global preRenameOldFileName=preRenameOldFileName ;~Old file name
Global postRenameFileToRenameID=postRenameFileToRenameID ;~ID of the file to rename
Global postRenameFilesParentFolderID=postRenameFilesParentFolderID ;~ID of the file's parent folder
Global postRenameNewFileName=postRenameNewFileName ;~New file name
Global postRenameOldFileName=postRenameOldFileName ;~New file name
Global preRenameFolderFolderID=preRenameFolderFolderID ;~ID of the folder to rename
Global preRenameFolderParentFolderID=preRenameFolderParentFolderID ;~ID of the folder's parent folder
Global preRenameFolderOldFolderName=preRenameFolderOldFolderName ;~Old folder name
Global preRenameFolderNewFolderName=preRenameFolderNewFolderName ;~New folder name
Global postRenameFolderFolderID=postRenameFolderFolderID ;~ID of the folder to rename
Global postRenameFolderParentFolderID=postRenameFolderParentFolderID ;~ID of the folder's parent folder
Global postRenameFolderOldFolderName=postRenameFolderOldFolderName ;~Old folder name
Global postRenameFolderNewFolderName=postRenameFolderNewFolderName ;~New folder name
Global preShareParentFolderID=preShareParentFolderID ;~ID of folder to share file from
Global preShareDestinationFolderID=preShareDestinationFolderID ;~ID of folder to share file to
Global postShareParentFolderID=postShareParentFolderID ;~ID of folder to share file from
Global postShareDestinationFolderID=postShareDestinationFolderID ;~ID of folder to share file to
Global preStateParentFolderID=preStateParentFolderID ;~ID of the file's parent folder
Global preStateTransitionID=preStateTransitionID ;~ID of the transition (state change) to perform
Global preStateDestinationStateName=preStateDestinationStateName ;~Name of the destination state
Global preStateSourceStateID=preStateSourceStateID ;~ID of the source state
Global preStateDestinationStateID=preStateDestinationStateID ;~ID of the Destination state
Global postStateParentFolderID=postStateParentFolderID ;~ID of the file's parent folder
Global postStateTransitionID=postStateTransitionID ;~ID of the transition (state change) to perform
Global postStateDestinationStateName=postStateDestinationStateName ;~Name of the destination state
Global postStateSourceStateID=postStateSourceStateID ;~ID of the source state
Global postStateDestinationStateID=postStateDestinationStateID ;~ID of the Destination state
Global preUndoLockParentFolderID=preUndoLockParentFolderID ;~ID of the file's parent folder
Global postUndoLockParentFolderID=postUndoLockParentFolderID ;~ID of the file's parent folder
Global preUnlockParentFolderID=preUnlockParentFolderID ;~ID of the file's parent folder
Global postUnlockParentFolderID=postUnlockParentFolderID ;~ID of the file's parent folder
Global preLabelFileID=preLabelFileID ;~ID of file to set label on; 0 for folders
Global preLabelFolderID=preLabelFolderID ;~ID of file to set label on; 0 for folders
Global preLabelLabelID=preLabelLabelID ;~0 for EdmCmd_PreLabel; ID of the created label for EdmCmd_PostLabel
Global preLabelLabelName=preLabelLabelName ;~Label
Global preLabelLabelComment=preLabelLabelComment ;~Label
Global preLabelFileName=preLabelFileName ;~Path to file or folder to create label for; note that this member will only contain the file name without path when file labels are created via the API, since that is not done within the context of a folder
Global preLabelCreatedRecursively=preLabelCreatedRecursively ;~Non 0 if label is created recursively for this folder, 0 otherwise
Global postLabelkParentFolderID=postLabelkParentFolderID ;~ID of the file's parent folder
Global postLabelFileID=postLabelFileID ;~ID of file to set label on; 0 for folders
Global postLabelFolderID=postLabelFolderID ;~ID of file to set label on; 0 for folders
Global postLabelLabelID=postLabelLabelID ;~0 for EdmCmd_postLabel; ID of the created label for EdmCmd_PostLabel
Global postLabelLabelName=postLabelLabelName ;~Label
Global postLabelComment=postLabelComment ;~Comment
Global postLabelFileName=postLabelFileName ;~Path to file or folder to create label for; note that this member will only contain the file name without path when file labels are created via the API, since that is not done within the context of a folder
Global postLabelCreatedRecursively=postLabelCreatedRecursively ;~Non 0 if label is created recursively for this folder, 0 otherwise
Global preLabelDeleteLabelID=preLabelDeleteLabelID ;~ID of the label
Global preLabelDeleteLabel=preLabelDeleteLabel ;~label
Global postLabelDeleteLabelID=postLabelDeleteLabelID ;~ID of the label
Global postLabelDeleteLabel=postLabelDeleteLabel ;~label
Global preLabelModifyLabelID=preLabelModifyLabelID ;~ID of the label
Global preLabelModifiyLabel=preLabelModifiyLabel ;~label
Global preLabelModifiyComment=preLabelModifiyComment ;~Comment
Global postLabelModofiyLabelID=postLabelModofiyLabelID ;~ID of the label
Global postLabelModifyLabel=postLabelModifyLabel ;~label
Global postLabelModifiyComment=postLabelModifiyComment ;~Comment
